### ISSUE TITLE
Where to write the code?

### ISSUE THREAD

**Issue by skbr1234** [amejiarosario/amejiarosario.github.io#2]
Can you share the project structure which needs to be followed for your [tutorial](http://adrianmejia.com/blog/2014/10/01/creating-a-restful-api-tutorial-with-nodejs-and-mongodb/#ExpressJS-and-Middlewares)? I couldn't follow you.

**Comment by amejiarosario** [comment]
That section is code examples. You can start writing code and following from this section on:
http://adrianmejia.com/blog/2014/10/01/creating-a-restful-api-tutorial-with-nodejs-and-mongodb/#Bootstrapping-ExpressJS

The full repo is on: https://github.com/amejiarosario/todoAPIjs
